dist: trusty
sudo: false

env:
  - distribution: windows
    version: "2k16"
  - distribution: windows
    version: "2k12r2"
  - distribution: windows
    version: "2k8r2"
  - distribution: windows
    version: "8.1"

before_install:
  # Download and install packer from hashicorp repository
 - wget https://releases.hashicorp.com/packer/1.3.2/packer_1.3.2_linux_amd64.zip
 - unzip -d ~/bin packer_1.3.2_linux_amd64.zip

before_script:
  - packer --version

script:
  # Validate packer templates files
  - packer validate ${distribution}-${version}/${version}.json
