---
- hosts: all
  tasks:
    - name: Windows | Install Virtio
      ansible.windows.win_package:
        path: 'E:\virtio-win-gt-x64.msi'
        product_id: BC3373F8-48ED-490D-9431-0D02425BA607
        state: present

    - name: Windows | Install Qemu Guest Agent and Spice agent
      ansible.windows.win_package:
        path: 'E:\virtio-win-guest-tools.exe'
        product_id: C4F21E04-480B-47BC-B592-4F9B43B124C8
        arguments: /install /passive /norestart
        state: present

    - name: Remove all current pagefiles
      community.windows.win_pagefile:
        remove_all: yes
        automatic: no
        state: absent

    - name: Defrag the C drive
      community.windows.win_defrag:
        include_volumes: C
        freespace_consolidation: true

    - name: Zero out freespace
      ansible.windows.win_powershell:
        script: |
          $FilePath = "c:\zero.tmp"
          $Volume = Get-WmiObject win32_logicaldisk -filter "DeviceID='C:'"
          $ArraySize = 64kb
          $SpaceToLeave = $Volume.Size * 0.05
          $FileSize = $Volume.FreeSpace - $SpacetoLeave
          $ZeroArray = new-object byte[]($ArraySize)

          $Stream = [io.File]::OpenWrite($FilePath)
          try {
              $CurFileSize = 0
              while ($CurFileSize -lt $FileSize) {
                  $Stream.Write($ZeroArray, 0, $ZeroArray.Length)
                  $CurFileSize += $ZeroArray.Length
              }
          }
          finally {
              if ($Stream) {
                  $Stream.Close()
              }
          }

          Remove-Item $FilePath
